logging:
  level:
    root: info
    org.springframework.boot.actuate: debug
    # logback.xml中的LOG_PATH的值对应logging.path的值
  path: ${user.dir}/logs

server:
  port: 8088

skyler:
    common:
      private-key: et34egddfdsfsdf
      public-key: safsffefefefdfdf
      target-callback-url: http://localhost:9999/v2/skyler/person/list
      excludeUrls:
        - /v1/login
        - /v1/list*
        - /v1/admin

spring:
  kafka:
#    47.98.189.37:9092
    bootstrap-servers: localhost:9092
    consumer:
      group-id: 0
    producer:
      batch-size: 65536
      buffer-memory: 524288
  profiles:
    active: @profileActive@

debug: true

spring.banner.image.location: /tao.jpg

#kafka:
#  consumer:
#    zookeeper:
#      connect: localhost:2181
#    servers: localhost:9092
#    enable:
#      auto:
#        commit: true
#    session:
#      timeout: 6000
#    auto:
#      commit:
#        interval: 100
#      offset:
#        reset: latest
#    topic: test
#    group:
#      id: test
#    concurrency: 10
#
#  producer:
#    servers: localhost:9092
#    retries: 0
#    batch:
#      size: 4096
#    linger: 1
#    buffer:
#      memory: 40960


management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: env,beans,mappings,loggers
        exclude: info
